//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheoryOfNumbers.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheoryOfNumbers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Über ähnelt.
        /// </summary>
        public static string strAbout {
            get {
                return ResourceManager.GetString("strAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        /// </summary>
        public static string strAbout2 {
            get {
                return ResourceManager.GetString("strAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berechnen ähnelt.
        /// </summary>
        public static string strCalculate {
            get {
                return ResourceManager.GetString("strCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primzahlenberechnung ähnelt.
        /// </summary>
        public static string strCalculatePrimeNumbers {
            get {
                return ResourceManager.GetString("strCalculatePrimeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung: ähnelt.
        /// </summary>
        public static string strDescription {
            get {
                return ResourceManager.GetString("strDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eweiterter Euklidischer Algorhitmus ähnelt.
        /// </summary>
        public static string strEEA {
            get {
                return ResourceManager.GetString("strEEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ggT(a,b) für c ermitteln ähnelt.
        /// </summary>
        public static string strEEADC {
            get {
                return ResourceManager.GetString("strEEADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löst eine diophantische Gleichung der Form ax + by =ggT(a,b) oder auch nur ax + by =c (ggT(a,b) muss c teilen). Wird benötigt um z.B. das multiplikative Inverse Element in einer algebraischen Struktur zu finden. In diesem Programm wird nur eine Lösung ausgewiesen, weitere lassen sich finden mit: x0 + (z * b)/ggT(a,b) und y0 - (a*z)/ggT(a,b) ähnelt.
        /// </summary>
        public static string strEuAlgo {
            get {
                return ResourceManager.GetString("strEuAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Beenden ähnelt.
        /// </summary>
        public static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bis: ähnelt.
        /// </summary>
        public static string strFrom {
            get {
                return ResourceManager.GetString("strFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Größter gemeinsamer Teiler (ggT) ähnelt.
        /// </summary>
        public static string strGGT {
            get {
                return ResourceManager.GetString("strGGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der größte gemeinsame Teiler von 2 Zahlen ist das größte Element aus der Vereinigunsmenge der Teilermengen von den beiden Zahlen. ähnelt.
        /// </summary>
        public static string strGGTDescription {
            get {
                return ResourceManager.GetString("strGGTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kleinstes gemeinsames Vielfaches (kgV) ähnelt.
        /// </summary>
        public static string strKGV {
            get {
                return ResourceManager.GetString("strKGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das kleinste Gemeinsame Vielfache von 2 Zahlen ist das kleinste Element aus der Vereinigungsmenge der gemeinsamen Vielfachen der beiden Zahlen. ähnelt.
        /// </summary>
        public static string strKGVDescription {
            get {
                return ResourceManager.GetString("strKGVDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt an, welche Zahlen teilerfremd (ggT(x, p)=1) zu p sind und im Bereich von 1 bis p liegen. ähnelt.
        /// </summary>
        public static string strPhiDescription {
            get {
                return ResourceManager.GetString("strPhiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hier können Sie alle Primzahlen berechnen, eine Zahl ist genau dann eine Primzahl, wenn die Mächtigkeit der Teilermenge der Zahl 2 ist bzw. es gilt |T(p)| = 2 ähnelt.
        /// </summary>
        public static string strPrimeDescription {
            get {
                return ResourceManager.GetString("strPrimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zerlegt die Zahl in ihre Primfaktoren mit den dazugehörigen Potenzen, z.B. 10 = 2^1 * 5 ^1 ähnelt.
        /// </summary>
        public static string strPrimeFactorization {
            get {
                return ResourceManager.GetString("strPrimeFactorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primfaktorzerlegung ähnelt.
        /// </summary>
        public static string strPrimeFactorization_ {
            get {
                return ResourceManager.GetString("strPrimeFactorization_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ergebnis: ähnelt.
        /// </summary>
        public static string strResult {
            get {
                return ResourceManager.GetString("strResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zahlentheorie ähnelt.
        /// </summary>
        public static string strTitle {
            get {
                return ResourceManager.GetString("strTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Von: ähnelt.
        /// </summary>
        public static string strTo {
            get {
                return ResourceManager.GetString("strTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie gültige Werte ein! ähnelt.
        /// </summary>
        public static string strVaildValues {
            get {
                return ResourceManager.GetString("strVaildValues", resourceCulture);
            }
        }
    }
}
